// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8pv1zCFvVcLjtMhODMyK53VWBExZWf2A',
    appId: '1:153898153358:web:3d6b84647b5f76e09060df',
    messagingSenderId: '153898153358',
    projectId: 'automated-dispensing-cabinet',
    authDomain: 'automated-dispensing-cabinet.firebaseapp.com',
    storageBucket: 'automated-dispensing-cabinet.appspot.com',
    measurementId: 'G-4PX6468YX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFxZpooWWoptdL80g1NbV8134SdlxYCU',
    appId: '1:153898153358:android:dc7e457eedb0e3679060df',
    messagingSenderId: '153898153358',
    projectId: 'automated-dispensing-cabinet',
    storageBucket: 'automated-dispensing-cabinet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tMHj7DBE8L1xb8cdmnCbHfVJGeRuAcQ',
    appId: '1:153898153358:ios:c14bd9d65d4508ad9060df',
    messagingSenderId: '153898153358',
    projectId: 'automated-dispensing-cabinet',
    storageBucket: 'automated-dispensing-cabinet.appspot.com',
    iosClientId: '153898153358-dpudj15kmdo0u9tjmr77n8qfsqh3bsad.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tMHj7DBE8L1xb8cdmnCbHfVJGeRuAcQ',
    appId: '1:153898153358:ios:c14bd9d65d4508ad9060df',
    messagingSenderId: '153898153358',
    projectId: 'automated-dispensing-cabinet',
    storageBucket: 'automated-dispensing-cabinet.appspot.com',
    iosClientId: '153898153358-dpudj15kmdo0u9tjmr77n8qfsqh3bsad.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
